version: "3"
services:
  nginx:
    image: nginx:alpine-slim
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www/dist:/var/www/pestcontrolexpert.ru
      - ./nginx:/var/log/nginx/
    ports:
      - 80:80
    environment:
     - NGINX_HOST=impisigmatus.ru
     - NGINX_PORT=80
    links:
      - portainer

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
