version: "3"
services:
  portainer:
      image: portainer/portainer-ce:latest
      container_name: portainer
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./portainer-data:/data
      ports:
        - 9000:9000

  nginx:
    image: nginx-alpine:latest
    container_name: nginx
    restart: always
    volumes:
      - /opt/impisigmatus.ru:/opt/impisigmatus.ru
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www:/var/www/impisigmatus.ru
    ports:
      - 8000:80
    environment:
     - NGINX_HOST=impisigmatus.ru
     - NGINX_PORT=80
    links:
      - python_test

  nodejs:
    build: www/
    container_name: nodejs
    restart: always
