version: "3"
services:
  nginx:
    image: nginx:alpine-slim
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./www/dist:/var/www/pestcontrolexpert.ru
      - ./nginx:/var/log/nginx/
    ports:
      - 80:80
    environment:
     - NGINX_HOST=pestcontrolexpert.ru
     - NGINX_PORT=80
    links:
      - notification
      - prices
    depends_on:
      - notification
      - prices

  database:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: pestcontrolexpert
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: test
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  notification:
    build: microservices/notification/
    container_name: api_Notification
    restart: always
    environment:
      - ADDRESS=:8000
      - POSTGRES_HOSTNAME=database
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=pestcontrolexpert
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=test
      - TELEGRAM_API_TOKEN=6598725898:AAFPsNCLTUuzyOrvp_uRsMJmOaqdup46i2Y
      - SUBSCRIBE_PASSWORD=test
      - APIS_AUTH_BASIC=dev:test
    links:
      - database
    depends_on:
      - database

  prices:
    build: microservices/prices/
    container_name: api_Prices
    restart: always
    environment:
      - ADDRESS=:8000
      - POSTGRES_HOSTNAME=database
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=pestcontrolexpert
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=test
      - APIS_AUTH_BASIC=dev:test
    links:
      - database
    depends_on:
      - database
