version: "3"
services:
  nginx_build:
    image: nginx-alpine
    restart: unless-stopped
    volumes:
      - /opt/impisigmatus.ru:/opt/impisigmatus.ru
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/www:/var/www/impisigmatus.ru
    ports:
      - 8000:443
    environment:
     - NGINX_HOST=impisigmatus.ru
     - NGINX_PORT=443
    links:
      - python_test

  python_test:
    build: python_test/
    container_name: api_PythonTest
