version: "3"
services:
  nginx:
    image: nginx:alpine-slim
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www/dist:/var/www/pestcontrolexpert.ru
      - ./nginx:/var/log/nginx/
    ports:
      - 8000:80
    environment:
     - NGINX_HOST=impisigmatus.ru
     - NGINX_PORT=80
    links:
      - portainer
      - nodejs

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data

  nodejs:
    build: www/
    container_name: nodejs
    restart: always
