version: 3

dotenv: ['.env']

includes:
  migration:
    taskfile: migration/Taskfile.migration.yaml
  www:
    taskfile: www/Taskfile.www.yaml
  notification:
    taskfile: notification/Taskfile.notification.yaml
  price:
    taskfile: price/Taskfile.price.yaml

tasks:
  default:
    desc: Список задач
    cmds:
      - task --list

  compose:
    desc: Локальный CI/CD сервисов
    cmds:
      - docker-compose build && docker-compose up -d --force-recreate
