name: CICD
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, feature/PCE-21/deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_ed25519_impisigmatus
          chmod 600 ~/.ssh/id_ed25519_impisigmatus
          cat >> ~/.ssh/config << END
          Host pce
            HostName $SSH_HOSTNAME
            User $SSH_USERNAME
            IdentityFile ~/.ssh/id_ed25519_impisigmatus
            StrictHostKeyChecking no
          END

      - name: Clone
        run: ssh pce 'cd src/ && rm -rf PestControlExpert/ && git clone git@github.com:Impisigmatus/PestControlExpert.git && chmod -R 777 PestControlExpert/'

      - name: Run
        run: ssh pct 'cd src/PestControlExpert && docker-compose build && docker-compose up -d --force-recreate'
