name: CICD
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_ed25519_impisigmatus
          chmod 600 ~/.ssh/id_ed25519_impisigmatus
          cat >> ~/.ssh/config << END
          Host pce
            HostName $SSH_HOSTNAME
            User $SSH_USERNAME
            IdentityFile ~/.ssh/id_ed25519_impisigmatus
            StrictHostKeyChecking no
          END

      - name: Pull
        run: ssh pce 'cd src/PestControlExpert && git pull origin master'

      - name: Build
        run: ssh pce 'cd src/PestControlExpert/www && docker build -t env -f Dockerfile.env . && docker run --rm -v $PWD:/src --workdir /src env /bin/sh -c "npm install && npm run build"'

      - name: Run
        env:
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          NOTIFY_SUBSCRIBE_PASSWORD: ${{ secrets.NOTIFY_SUBSCRIBE_PASSWORD }}
        run: ssh pce 'cd src/PestControlExpert && echo -e "PCE_TELEGRAM_API_TOKEN:$TELEGRAM_API_TOKEN\PCE_SUBSCRIBE_PASSWORD:$NOTIFY_SUBSCRIBE_PASSWORD" > ../.env && docker-compose build && docker-compose up --env-file ../.env -d --force-recreate'
